server:
  port: 8080
  servlet:
    context-path: /product-data

spring:
  application:
    name: product-data
  cloud:
    bootstrap:
      enabled: true
    gcp:
      project-id: store-valesolution
      pubsub:
        enabled: false
      #        subscriber:
      #          executor-threads: 1
      #          parallel-pull-count: 1
      #          flow-control:
      #            max-outstanding-element-count: 2
      #            limit-exceeded-behavior: block
      trace:
        enabled: false
      logging:
        enabled: false
  data:
    mongodb:
      username: mongoUser
      password: mongoPass
      host: localhost
      port: 27017
      database: app
      authentication-database: admin
  security:
    user:
      name: teste
      password: teste
management:
  endpoint:
    health:
      show-details: NEVER


